<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        @page { margin: 18mm 16mm; size: A4 portrait; }
        body { font-family: DejaVu Sans, sans-serif; color: #1f2937; font-size: 12px; }
        .page-break { page-break-after: always; }
        .cover { text-align: center; padding-top: 32mm; }
        .logo { width: 58px; height: 58px; margin: 0 auto 10px; color: #4f46e5; }
        h1 { margin: 0; font-size: 27px; }
        h2 { margin: 8px 0 0; color: #4b5563; font-size: 17px; }
        .meta { margin-top: 20px; line-height: 1.8; color: #374151; }
        .block { border: 1px solid #e5e7eb; border-radius: 8px; margin-bottom: 10px; overflow: hidden; }
        .head { background: #f3f4f6; padding: 6px 10px; font-size: 11px; font-weight: bold; }
        .body { padding: 10px; font-size: 12px; line-height: 1.6; }
        .body p { margin: 0 0 8px; }
        .credits { text-align: center; padding-top: 0; margin-top: 0; }
    </style>
</head>
<body>
    <section class="cover page-break">
        <div class="logo">
            <svg viewBox="0 0 24 24" width="58" height="58" xmlns="http://www.w3.org/2000/svg">
                <circle cx="10.5" cy="10.5" r="6.5" fill="none" stroke="currentColor" stroke-width="2.5"></circle>
                <line x1="15.2" y1="15.2" x2="21" y2="21" stroke="currentColor" stroke-width="2.8" stroke-linecap="round"></line>
            </svg>
        </div>
        <h1>{{ $app_name }}</h1>
        <h2>{{ $project->name }} — Transcribed Text PDF</h2>
        <div class="meta">
            <div><strong>Description:</strong> {{ $project->description ?: 'No description.' }}</div>
            <div><strong>Total pages:</strong> {{ $pages->count() }}</div>
            <div><strong>Generated at:</strong> {{ $generated_at->format('Y-m-d H:i') }}</div>
        </div>
    </section>

    <section>
        <div class="block">
            <div class="head">Transcribed text (continuous)</div>
            <div class="body">
                @php($hasAny = false)
                @foreach ($pages as $page)
                    @if (!empty(trim(strip_tags($page['transcribed_text']))))
                        @php($hasAny = true)
                        {!! $page['transcribed_text'] !!}
                        @if (!$loop->last)<br><br>@endif
                    @endif
                @endforeach
                @if (!$hasAny)
                    <em>No content.</em>
                @endif
            </div>
        </div>
    </section>

    <section class="credits">
        
        <p>
            Generated by {{ $app_name }}.<br>
            Project owner: Anderson Deizepe<br>
            Support: anderson@deizepe.com.br
        </p>
    </section>
</body>
</html>
