<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        @page { margin: 12mm 10mm; size: A4 landscape; }
        body { font-family: DejaVu Sans, sans-serif; color: #1f2937; font-size: 10px; }
        .page-break { page-break-after: always; }
        .doc-header { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
        .doc-header td { vertical-align: top; }
        .logo { width: 26px; height: 26px; color: #4f46e5; }
        .doc-title { font-size: 14px; font-weight: bold; margin: 0; }
        .doc-sub { font-size: 10px; color: #4b5563; margin: 1px 0 0; }
        .doc-meta { text-align: right; color: #4b5563; font-size: 9px; line-height: 1.4; }
        .sheet-title { font-size: 12px; font-weight: bold; margin: 0 0 2px; }
        .sheet-name { color: #6b7280; margin-bottom: 6px; font-size: 9px; }
        .content-grid { width: 100%; border-collapse: collapse; table-layout: fixed; }
        .content-grid td { vertical-align: top; }
        .col-image { width: 40%; padding-right: 8px; }
        .col-text { width: 60%; }
        .img-wrap { border: 1px solid #d1d5db; border-radius: 4px; padding: 4px; text-align: center; }
        .img-wrap img { max-width: 100%; max-height: 145mm; object-fit: contain; }
        .text-card { border: 1px solid #e5e7eb; border-radius: 4px; margin-bottom: 6px; overflow: hidden; }
        .text-head { background: #f3f4f6; padding: 4px 6px; font-size: 9px; font-weight: bold; color: #374151; }
        .text-body { padding: 6px; font-size: 9px; line-height: 1.35; color: #111827; }
        .text-body p { margin: 0 0 4px; }
        .credits { margin-top: 0; border-top: 1px solid #e5e7eb; padding-top: 0; text-align: center; color: #4b5563; font-size: 9px; line-height: 1.5; }
    </style>
</head>
<body>
    @foreach ($pages as $page)
        <section class="{{ $loop->last ? '' : 'page-break' }}">
            @if ($loop->first)
            <table class="doc-header">
                <tr>
                    <td>
                        <svg class="logo" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                            <circle cx="10.5" cy="10.5" r="6.5" fill="none" stroke="currentColor" stroke-width="2.5"></circle>
                            <line x1="15.2" y1="15.2" x2="21" y2="21" stroke="currentColor" stroke-width="2.8" stroke-linecap="round"></line>
                        </svg>
                    </td>
                    <td style="width: 58%;">
                        <p class="doc-title">{{ $app_name }} — {{ $project->name }}</p>
                        <p class="doc-sub">{{ $project->description ?: 'No description.' }}</p>
                    </td>
                    <td class="doc-meta">
                        Total pages: {{ $pages->count() }}<br>
                        Generated: {{ $generated_at->format('Y-m-d H:i') }}
                    </td>
                </tr>
            </table>
            @endif

            <div class="sheet-title">Page {{ $page['page_number'] }}</div>
            <div class="sheet-name">{{ $page['original_filename'] }}</div>
            <table class="content-grid">
                <tr>
                    <td class="col-image">
                        <div class="img-wrap">
                            @if ($page['image_data_url'])
                                <img src="{{ $page['image_data_url'] }}" alt="Page image">
                            @else
                                <em>Image unavailable.</em>
                            @endif
                        </div>
                    </td>
                    <td class="col-text">
                        <div class="text-card">
                            <div class="text-head">Original text</div>
                            <div class="text-body">{!! $page['original_text'] ?: '<em>No content.</em>' !!}</div>
                        </div>
                        <div class="text-card">
                            <div class="text-head">Transcribed (contemporary)</div>
                            <div class="text-body">{!! $page['transcribed_text'] ?: '<em>No content.</em>' !!}</div>
                        </div>
                        <div class="text-card">
                            <div class="text-head">Notes</div>
                            <div class="text-body">{!! $page['notes'] ?: '<em>No notes.</em>' !!}</div>
                        </div>
                    </td>
                </tr>
            </table>

            @if ($loop->last)
                <div class="credits">
                    
                    Generated by {{ $app_name }}.<br>
                    Project owner: Anderson Deizepe<br>
                    Support: anderson@deizepe.com.br
                </div>
            @endif
        </section>
    @endforeach
</body>
</html>
