<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $app_name }} - {{ $project->name }} (Word)</title>
    <style>
        @page Section1 {
            size: 841.9pt 595.3pt;
            mso-page-orientation: landscape;
            margin: 40pt 34pt 40pt 34pt;
        }
        div.Section1 { page: Section1; }
        body { font-family: Calibri, Arial, sans-serif; color: #1f2937; font-size: 11pt; }
        .doc-header { width: 100%; border-collapse: collapse; margin-bottom: 10pt; }
        .doc-header td { vertical-align: top; }
        .logo { width: 28pt; height: 28pt; color: #4f46e5; }
        .title { font-size: 15pt; font-weight: bold; margin: 0; }
        .sub { font-size: 10pt; color: #4b5563; margin: 2pt 0 0; }
        .meta { text-align: right; font-size: 9pt; color: #4b5563; line-height: 1.35; }
        .sheet { page-break-after: always; }
        .sheet:last-of-type { page-break-after: auto; }
        .sheet-title { font-size: 13pt; font-weight: bold; margin-bottom: 2pt; }
        .sheet-name { color: #6b7280; font-size: 9pt; margin-bottom: 8pt; }
        .grid { width: 100%; border-collapse: collapse; table-layout: fixed; }
        .grid td { vertical-align: top; }
        .col-image { width: 40%; padding-right: 8pt; }
        .col-text { width: 60%; }
        .img-wrap { border: 1px solid #d1d5db; padding: 4pt; text-align: center; }
        .img-wrap img { display: block; margin: 0 auto; }
        .card { border: 1px solid #e5e7eb; margin-bottom: 6pt; }
        .card-head { background: #f3f4f6; padding: 4pt 6pt; font-size: 9pt; font-weight: bold; }
        .card-body { padding: 6pt; font-size: 9pt; line-height: 1.35; }
        .card-body p { margin: 0 0 4pt; }
        .credits { margin-top: 8pt; border-top: 1px solid #e5e7eb; padding-top: 6pt; text-align: center; font-size: 9pt; color: #4b5563; line-height: 1.45; }
    </style>
</head>
<body>
<div class="Section1">
@foreach ($pages as $page)
    <section class="sheet">
        @if ($loop->first)
        <table class="doc-header">
            <tr>
                <td style="width: 34pt;">
                    <svg class="logo" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <circle cx="10.5" cy="10.5" r="6.5" fill="none" stroke="currentColor" stroke-width="2.5"></circle>
                        <line x1="15.2" y1="15.2" x2="21" y2="21" stroke="currentColor" stroke-width="2.8" stroke-linecap="round"></line>
                    </svg>
                </td>
                <td>
                    <p class="title">{{ $app_name }} — {{ $project->name }}</p>
                    <p class="sub">{{ $project->description ?: 'No description.' }}</p>
                </td>
                <td class="meta">
                    Total pages: {{ $pages->count() }}<br>
                    Generated: {{ $generated_at->format('Y-m-d H:i') }}
                </td>
            </tr>
        </table>
        @endif

        <div class="sheet-title">Page {{ $page['page_number'] }}</div>
        <div class="sheet-name">{{ $page['original_filename'] }}</div>

        <table class="grid">
            <tr>
                <td class="col-image">
                    <div class="img-wrap">
                        @if ($page['image_data_url'])
                            <img src="{{ $page['image_data_url'] }}" alt="Page image" width="300" style="width:300px;height:auto;max-width:300px;">
                        @else
                            <em>Image unavailable.</em>
                        @endif
                    </div>
                </td>
                <td class="col-text">
                    <div class="card">
                        <div class="card-head">Original text</div>
                        <div class="card-body">{!! $page['original_text'] ?: '<em>No content.</em>' !!}</div>
                    </div>
                    <div class="card">
                        <div class="card-head">Transcribed (contemporary)</div>
                        <div class="card-body">{!! $page['transcribed_text'] ?: '<em>No content.</em>' !!}</div>
                    </div>
                    <div class="card">
                        <div class="card-head">Notes</div>
                        <div class="card-body">{!! $page['notes'] ?: '<em>No notes.</em>' !!}</div>
                    </div>
                </td>
            </tr>
        </table>

        @if ($loop->last)
        <div class="credits">
            Generated by {{ $app_name }}.<br>
            Project owner: Anderson Deizepe<br>
            Support: anderson@deizepe.com.br
        </div>
        @endif
    </section>
@endforeach
</div>
</body>
</html>
