<?php
// Variables
return [
  "creatorName" => "Anderson Deizepe",
  "creatorUrl" => "https://github.com/Deizepe",
  "templateName" => "AiPaleograph",
  "templateSuffix" => "Digital Paleography",
  "templateVersion" => "2.0.0",
  "templateFree" => true,
  "templateDescription" => "AiPaleograph is a digital paleography workspace to organize manuscript projects, transcribe page images with AI via OpenRouter, and produce contemporary-language renditions.",
  "templateKeyword" => "ai paleography, manuscript transcription, openrouter, digital humanities, laravel",
  "licenseUrl" => "https://themeselection.com/license/",
  "livePreview" => "",
  "productPage" => "",
  "support" => "mailto:anderson@deizepe.com.br",
  "adminTemplates" => "",
  "bootstrapDashboard" => "",
  "ogTitle" => "AiPaleograph - Digital Paleography with AI",
  "ogImage" => "",
  "ogType" => "website",
  "documentation" => "",
  "repository" => "https://github.com/Deizepe/AiPaleograph",
  "gitRepo" => "https://github.com/Deizepe/AiPaleograph.git",
  "gitRepoAccess" => "",
  "githubFreeUrl" => "https://github.com/Deizepe",
  "facebookUrl" => "",
  "twitterUrl" => "",
  "githubUrl" => "https://github.com/Deizepe",
  "dribbbleUrl" => "",
  "instagramUrl" => ""
];